---
apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop
  annotations:
    net.beta.kubernetes.io/network-policy: |
      {
        "ingress": {
          "isolation": "DefaultDeny"
        }
      }

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
