# Ingress controller routing request to the front-end service 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop-ingress
  namespace: sock-shop
  labels:
    app: front-end
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: sockshop.sapphireaura.com.ng
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: front-end
            port:
              number: 80
  tls:
  - hosts:
      - sockshop.sapphireaura.com.ng
    secretName: letsencrypt-production
    
