# Configuration to issue a let's encrypt certificate for the socks shop domain name.
# Note: Domain name is 'zenitugo.com.ng'  and sub-domain name is 'www'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop-ingress
  namespace: sock-shop
  labels:
    app: front-end
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: production
spec:
  tls:
  - hosts:
      - sockshop.zenitugo.com.ng
    secretName: letsencrypt-production
  rules:
  - host: sockshop.zenitugo.com.ng
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: front-end
            port:
              number: 80
  ingressClassName: nginx  