variable "cidr_block" {}
variable "region" {}
variable "public-subnets" {}
variable "private-subnets" {}
variable "cluster" {}
variable "node-group" {}
variable "instance_type" {}
variable "key_name" {}
variable "cluster-rolename" {}
variable "node-role-name" {}
variable "key_filename" {}
variable "sg-name" {}
variable "addon_name" {}
variable "role_name" {}
