---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sockshop-cert
  namespace: default
spec:
  secretName: sockshop-tls  #This is where the certificate will be stored.
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  dnsNames:
    - "*.sapphireaura.com.ng"    #This will be a wild card certificate
    - "*.sapphireaura.com.ng"
 