# Create a production cluster issuer for let's encrypt
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  #Acme server url
    email: ugochiukaegbu17@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production         #Name of secret used to store the ACME account private key
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx     