# Create a production cluster issuer for let's encrypt
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  #Acme server url
    email: ugochiukaegbu17@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod         #Name of secret used to store the ACME account private key
  #solvers:
    #- dns01:
     #   route53:
      #    region: eu-west-1
       #   accessKeyID: "AWS_ACCESS_KEY_ID" 
        #  secretAccessKeySecretRef:
         #   name: aws_secret_key
          #  key: AWS_SECRET_ACCESS_KEY        