name: Destroy terraform infrastructure
on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 50
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: eu-west-1
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3               

            - name: Initialize terraform
              run: terraform init
              
            - name: Get Terraform state resources
              run: terraform init -backend-config="bucket=zenitugo21" -backend-config="dynamodb_table=ugdatabase"

            - name: Destroy terraform resources
              run: terraform destroy -auto-approve