name: Workflow to create EKS and install ArgoCD

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ] 

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 50
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: Install kubectl
              uses: azure/setup-kubectl@v3
              with:
                version: 'v1.29.0'
              id: Install
            - name: Install helm
              uses: azure/setup-helm@v4.1.0
              with:
                version: 'v3.14.0'
              id: helm
              
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: eu-west-1
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3               

            - name: Create S3 buckets and dynamodb table
              run: |
                echo "Creating s3 bucket and dynamodb table"
                cd terraform-s3-db
                cd rootmodules
                terraform init
                terraform plan -var-file="terraform.tfvars"
                terraform apply -auto-approve

            - name: Create an EKS cluster
              run: |
                echo "Creating an eks cluster"
                cd terraform-eks
                cd devEnvironment
                terraform init
                terraform plan -var-file="terraform.tfvars"
                terraform apply -auto-approve

            - name: Update kube config
              run: aws eks update-kubeconfig --name mycluster

            - name: Create Namespace in EKS
              run: |
                cd manifest
                echo "Creating namespace"
                kubectl apply -f namespace.yml

            - name: Install ArgoCD in EKS Cluster
              run: |
                echo "Installing argocd in eks cluster"
                kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.2/manifests/install.yaml
            
            
            - name: Install Nginx Ingress Controller with helm in EKS cluster
              run:
                echo "Installing nginx ingress controller"
                helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
                helm repo update
                helm install nginx ingress-nginx/ingress-nginx --namespace ingress-nginx 

            - name: Download Cert Manager Repo in EKS cluster
              run: 
                echo "Installing cert manager in eks cluster"
                helm repo add jetstack https://charts.jetstack.io
                helm repo update

            - name: Install CRD for cert manager
              run: |
                kubectl apply -n cert-manager --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.14/deploy/manifest/00-crds.yml
                
            - name: Install Cert Manager using Helm
              run:
                helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v0.14

            - name: Send notification to slack on the status of my pipeline
              uses: slackapi/slack-github-action@v1.24.0
              with:
                payload: |
                  {
                    "text": "Github Actions Complete, CI pipeline successful"
                   }
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
              id: Slack      


                           