name: Slack-Github Action
on: [push]
jobs:
   Slack-Notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to slack on the status of my pipeline
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
                "text": "Github Actions Complete, CI pipeleine successful"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        id: Slack